### ISSUE TITLE
Add error notification UX

### ISSUE THREAD

**Issue by hamidra** [paritytech/governance-ui#209]
We need to have an error notification for scenarios where something goes wrong during the delegation process.
Mainly there can be two types of errors:
- Validation error: This happens when there is an issue in the modal when the delegation happens. (e.g. delegation is not possible because the user does not have free balance to delegate?!)
- Chain submission error: while submitting the transaction for some reason fails (This can be shown as an overlay notification box?)

**Comment by jeluard** [comment]
Note that it is currently implemented as a `snackbar`
