### ISSUE TITLE
Add UI element allowing to gather feedback

### ISSUE THREAD

**Issue by jeluard** [paritytech/governance-ui#218]
Users should be able to provide feedback from the app, by clicking on a link/button that would redirect to a 3rd party website.

https://polkadot-staking-dashboard.canny.io/feature-requests

**Comment by dnlklmn** [comment]
staking dashboard uses canny.io, but i can't sign up to create an account, need to get approval from security team
could you look into it @jeluard or should i?

**Comment by dnlklmn** [comment]
or we can just let people open issues on github. canny is friendlier if we're shooting for a broader audience though

**Comment by dnlklmn** [comment]
footer added to the screens here [here](https://www.figma.com/proto/ke1WLYloUbG7XyO1N6OVBp/Open-Gov-MVP?page-id=85%3A13085&node-id=91-24038&viewport=1446%2C849%2C0.33&scaling=scale-down-width&starting-point-node-id=91%3A24038)

**Comment by jeluard** [comment]
Nice! Do you mind implementing them @dnlklmn ?

**Comment by dnlklmn** [comment]
done https://github.com/paritytech/governance-ui/pull/266
