### ISSUE TITLE
List main user scenarios

### ISSUE THREAD

**Issue by jeluard** [paritytech/governance-ui#257]

**Comment by dnlklmn** [comment]
WIP [in notion](https://www.notion.so/paritytechnologies/User-Scenarios-c4cce660608b478b8d2c30e32247b74c?pvs=4)
comments/notes/edits very welcome

**Comment by jeluard** [comment]
Have you considered scenarios where a user already has some delegations in place when browsing the main page? See `Stories` section from https://github.com/paritytech/governance-ui/milestone/1.

Also it might be useful to consider using this syntax to write scenarios: https://cucumber.io/docs/gherkin/reference/
It will help us implement automation for this.

**Comment by dnlklmn** [comment]
haven't yet, just got started with new (not-yet-delegating) user. 
happy to write it however its most useful, i have write gherkin tests before, not in a while though, will refresh my cucumber fingers
