### ISSUE TITLE
Add delegate address manually

### ISSUE THREAD

**Issue by dnlklmn** [paritytech/governance-ui#295]
check design in the [click dummy](https://www.figma.com/proto/ke1WLYloUbG7XyO1N6OVBp/Open-Gov-MVP?page-id=85%3A13085&node-id=91-24038&scaling=scale-down-width&starting-point-node-id=91%3A24038), click 'add address' btn in delegates action section

once you added a delegate manually, it should show up in your list of delegates, even if you don't delegate to them

https://user-images.githubusercontent.com/60112552/228476666-a3cf235b-6bc5-4e1a-a86b-816a173b16f8.mov

**Comment by jeluard** [comment]
Replace #221
