### ISSUE TITLE
Embed fonts

### ISSUE THREAD

**Issue by jeluard** [paritytech/governance-ui#296]
And get rid of https://github.com/paritytech/governance-ui/blob/382bd28928bb9f8dd6aaeae305c1504e710b3afb/src/index.html#L23

**Comment by dnlklmn** [comment]
added an <styles> @import ... </styles> block to App.tsx to import Unbounded and Inter
and started with most used text styles in tailwind.config.cjs just FYI

**Comment by jeluard** [comment]
Right, we want to get rid of this one too if possible

**Comment by hamidra** [comment]
@Julian is this something you can take care of?! Since I saw you already did it for unbounded:)
Initially when I was adding fonts I did not find the downloadable woffs and did not spend much time what are secure tools to convert!

**Comment by Julian** [comment]
Not sure!

**Comment by hamidra** [comment]
Sorry! I meant @jeluard our OpenGov hero:)
