### ISSUE TITLE
Improve wallet selection robustness

### ISSUE THREAD

**Issue by jeluard** [paritytech/governance-ui#348]
Periodically a `no extension was detected!` message pops up in the browser console during app initial load.
When this happens, no wallet is available as part of the wallet selection list. The connected account is also lost (no more show in the connect button), forcing the user to reselect an account.

I can reproduce this by just refreshing multiple times the whole app.

**Comment by hamidra** [comment]
Does this happen only on polkadot-js extension or on other extensions as well?

**Comment by jeluard** [comment]
I only have polkadot-js extension for now, so yes.
