### ISSUE TITLE
Delegation selection leads to 404 not found

### ISSUE THREAD

**Issue by wirednkod** [paritytech/governance-ui#450]
Start checking the temp deployment on https://paritytech.github.io/governance-ui/ and all selection of delegation leads to 404 not found (URL issue):

![image](https://user-images.githubusercontent.com/5408605/235672750-a58fc905-8c97-4b2d-af77-b7643da3b741.png)

**Comment by jeluard** [comment]
Do you mind detailing on what you click to get that? I can't reproduce for now.

**Comment by wirednkod** [comment]
Sure thing! Below a screencast that shows the steps followed:

[Screencast from 2023-05-02 16-35-16.webm](https://user-images.githubusercontent.com/5408605/235682449-353839fb-b830-4f9d-9bb0-b2b2f3fabbb2.webm)

**Comment by jeluard** [comment]
Thanks! Can reproduce now
