### ISSUE TITLE
Unresponsive "Delegate all tracks" buttons

### ISSUE THREAD

**Issue by wirednkod** [paritytech/governance-ui#452]
In volunteers delegate carousel, the "delegate all tracks" buttons are not clickable:

![image](https://user-images.githubusercontent.com/5408605/235673972-af57411c-39b2-4ea6-8bfc-0f627055cdd8.png)

**Comment by jeluard** [comment]
Are you connected? If not, it is intentionally disabled. UI might be improved here though probably.

**Comment by wirednkod** [comment]
I was probably not connected - UI is misleading then

**Comment by jeluard** [comment]
Fixed via #440
