### ISSUE TITLE
Local changes in delegates description not showing

### ISSUE THREAD

**Issue by Curu24** [paritytech/governance-ui#558]
Hello,

I tried to modify a delegate description on a local copy of this repo, but can't see any changes on the website running on localhost.
Here is what I tried:

- clone this repo https://github.com/paritytech/governance-ui
- run yarn install
- change ./assets/data/kusama/delegates.json (and same for Polkadot)
- run yarn dev

However on http://localhost:1234 I can only see the old version of the page like no files were edited. Maybe I just overlooked something, but I am not a frontend developer so I can't wrap my head around this.

As a note, I am trying to change the delegate description that is already merged into upstream if it plays any role in this.

Thanks a lot for your help!

**Comment by jeluard** [comment]
Hi @Curu24 , simply create a PR with your changes and once merged they will show up in the app. Including your local copy.
