### ISSUE TITLE
App crashes when Ethereum accounts are present in the account list

### ISSUE THREAD

**Issue by Tbaut** [paritytech/governance-ui#574]
This is most probably linked to an Ethereum account present in my account list.

To reproduce with talisman/subwallet create an ethereum account. Note that the pjs extension also supports them, but only when importing from a JSON (that was exported from e.g talisman/subwallet).

When I want to connect the extension it crashes
> with Unexpected Application Error! Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33

![image](https://github.com/paritytech/governance-ui/assets/33178835/a076a6d3-287a-4716-b022-25e98c5db399)

**Comment by hamidra** [comment]
Thanks for opening the issue! The app is using https://github.com/paritytech/polkadot-onboard for wallet connection.
Opened an issue to fix the issue in the polkadot-onboard lib

**Comment by jeluard** [comment]
@Tbaut Could you elaborate at what steps ih happen exactly? Right when you click on `talisman` in the list of wallets?
Does it work if you select a different wallet?

**Comment by Tbaut** [comment]
I use pjs/extension on the latest firefox. It happened the moment I clicked on "polkadot.js" in the onboard modal. But as I just wanted to reproduce, I'm facing another issue, the app never lets me send the connection request.
I deleted the entry so that pjs/extension wouldn't remember I gave access to `paritytech,github.io`, also I deleted all the local storage entries. The Dapp doesn't let me connect.

https://github.com/paritytech/governance-ui/assets/33178835/ca785fd0-6d58-4a36-a9bb-f38398d74e4c

**Comment by jeluard** [comment]
This one is a known issue of `polkadot-onboard`. Under some circumstances, wallet aren't detected.

**Comment by hamidra** [comment]
This was indeed a bug in the app and the upstream ```@polkadot-onboard``` is intended to be neutral re what accounts are injected by wallets.
I submitted a PR #643 to fix this in the app and closed the [issue](https://github.com/paritytech/polkadot-onboard/issues/97) in the upstream lib.
